In [2]:
# Install camelot with OpenCV & PDF plotting dependencies
!pip install "camelot-py[cv]"
# Or pip install "camelot-py[all]"

Collecting camelot-py[cv]
  Downloading camelot_py-2.0.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: click>=8.0.1 in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from camelot-py[cv]) (8.3.1)
Requirement already satisfied: numpy>=1.26.1 in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from camelot-py[cv]) (1.26.4)
Requirement already satisfied: openpyxl>=3.1.0 in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from camelot-py[cv]) (3.1.5)
Requirement already satisfied: pandas>=2.2.2 in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from camelot-py[cv]) (3.0.5)
Requirement already satisfied: tabulate>=0.9.0 in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from camelot-py[cv]) (0.10.0)
Collecting opencv-python-headless>=4.7.0.68 (from camelot-py[cv])
  Downloading opencv_python_headless-5.0.0.93-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: pypdfium2>=4 in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from camelot-py[cv]) (5.13.0)
Requirement already satisfied: pillow>=10.4.0 in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from camelot-py[cv]) (12.3.0)
Collecting playa-pdf>=0.8.1 (from camelot-py[cv])
  Downloading playa_pdf-1.1.0-cp311-cp311-win_amd64.whl.metadata (27 kB)
Requirement already satisfied: colorama in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from click>=8.0.1->camelot-py[cv]) (0.4.6)
Collecting numpy>=1.26.1 (from camelot-py[cv])
  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: et-xmlfile in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from openpyxl>=3.1.0->camelot-py[cv]) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from pandas>=2.2.2->camelot-py[cv]) (2.8.2)
Requirement already satisfied: tzdata in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from pandas>=2.2.2->camelot-py[cv]) (2023.3)
Requirement already satisfied: mypy-extensions in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from playa-pdf>=0.8.1->camelot-py[cv]) (1.0.0)
Requirement already satisfied: six>=1.5 in c:\users\sudar\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.2->camelot-py[cv]) (1.16.0)
Downloading opencv_python_headless-5.0.0.93-cp37-abi3-win_amd64.whl (43.8 MB)
   ---------------------------------------- 0.0/43.8 MB ? eta -:--:--
    --------------------------------------- 1.0/43.8 MB 6.3 MB/s eta 0:00:07
   - -------------------------------------- 1.8/43.8 MB 4.4 MB/s eta 0:00:10
   -- ------------------------------------- 2.6/43.8 MB 4.2 MB/s eta 0:00:10
   --- ------------------------------------ 3.4/43.8 MB 4.3 MB/s eta 0:00:10
   --- ------------------------------------ 4.2/43.8 MB 4.3 MB/s eta 0:00:10
   ---- ----------------------------------- 5.0/43.8 MB 4.0 MB/s eta 0:00:10
   ----- ---------------------------------- 5.8/43.8 MB 4.1 MB/s eta 0:00:10
   ----- ---------------------------------- 6.6/43.8 MB 4.1 MB/s eta 0:00:10
   ------ --------------------------------- 7.3/43.8 MB 4.0 MB/s eta 0:00:10
   ------- -------------------------------- 8.4/43.8 MB 4.1 MB/s eta 0:00:09
   -------- ------------------------------- 9.2/43.8 MB 4.0 MB/s eta 0:00:09
   --------- ------------------------------ 10.0/43.8 MB 4.1 MB/s eta 0:00:09
   --------- ------------------------------ 10.5/43.8 MB 3.9 MB/s eta 0:00:09
   ---------- ----------------------------- 11.5/43.8 MB 4.0 MB/s eta 0:00:09
   ----------- ---------------------------- 12.3/43.8 MB 4.0 MB/s eta 0:00:08
   ----------- ---------------------------- 12.8/43.8 MB 4.0 MB/s eta 0:00:08
   ------------ --------------------------- 13.9/43.8 MB 4.0 MB/s eta 0:00:08
   ------------- -------------------------- 14.7/43.8 MB 4.0 MB/s eta 0:00:08
   -------------- ------------------------- 15.7/43.8 MB 4.0 MB/s eta 0:00:08
   -------------- ------------------------- 16.3/43.8 MB 3.9 MB/s eta 0:00:08
   --------------- ------------------------ 17.3/43.8 MB 4.0 MB/s eta 0:00:07
   ---------------- ----------------------- 18.1/43.8 MB 4.0 MB/s eta 0:00:07
   ---------------- ----------------------- 18.6/43.8 MB 4.0 MB/s eta 0:00:07
   ------------------ --------------------- 19.9/43.8 MB 4.0 MB/s eta 0:00:07
   ------------------ --------------------- 20.7/43.8 MB 4.0 MB/s eta 0:00:06
   ------------------- -------------------- 21.2/43.8 MB 4.0 MB/s eta 0:00:06
   -------------------- ------------------- 22.3/43.8 MB 4.0 MB/s eta 0:00:06
   --------------------- ------------------ 23.1/43.8 MB 4.0 MB/s eta 0:00:06
   --------------------- ------------------ 23.9/43.8 MB 4.0 MB/s eta 0:00:06
   ---------------------- ----------------- 24.6/43.8 MB 3.9 MB/s eta 0:00:05
   ----------------------- ---------------- 25.4/43.8 MB 4.0 MB/s eta 0:00:05
   ----------------------- ---------------- 26.2/43.8 MB 3.9 MB/s eta 0:00:05
   ------------------------ --------------- 27.3/43.8 MB 4.0 MB/s eta 0:00:05
   ------------------------- -------------- 28.0/43.8 MB 4.0 MB/s eta 0:00:04
   -------------------------- ------------- 28.8/43.8 MB 3.9 MB/s eta 0:00:04
   --------------------------- ------------ 29.6/43.8 MB 4.0 MB/s eta 0:00:04
   --------------------------- ------------ 30.4/43.8 MB 4.0 MB/s eta 0:00:04
   ---------------------------- ----------- 31.2/43.8 MB 4.0 MB/s eta 0:00:04
   ---------------------------- ----------- 31.7/43.8 MB 4.0 MB/s eta 0:00:04
   ----------------------------- ---------- 32.8/43.8 MB 4.0 MB/s eta 0:00:03
   ------------------------------ --------- 33.3/43.8 MB 3.9 MB/s eta 0:00:03
   ------------------------------- -------- 34.3/43.8 MB 4.0 MB/s eta 0:00:03
   -------------------------------- ------- 35.1/43.8 MB 3.9 MB/s eta 0:00:03
   -------------------------------- ------- 35.9/43.8 MB 3.9 MB/s eta 0:00:03
   --------------------------------- ------ 37.0/43.8 MB 4.0 MB/s eta 0:00:02
   ---------------------------------- ----- 37.5/43.8 MB 4.0 MB/s eta 0:00:02
   ----------------------------------- ---- 38.5/43.8 MB 4.0 MB/s eta 0:00:02
   ----------------------------------- ---- 39.3/43.8 MB 3.9 MB/s eta 0:00:02
   ------------------------------------ --- 40.1/43.8 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 40.9/43.8 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 41.9/43.8 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 42.7/43.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  43.3/43.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  43.8/43.8 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 43.8/43.8 MB 3.9 MB/s eta 0:00:00
Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
Downloading playa_pdf-1.1.0-cp311-cp311-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.2 MB 7.1 MB/s eta 0:00:02
   ---------- ----------------------------- 2.1/8.2 MB 4.7 MB/s eta 0:00:02
   -------------- ------------------------- 2.9/8.2 MB 4.8 MB/s eta 0:00:02
   ----------------- ---------------------- 3.7/8.2 MB 4.4 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.2 MB 4.4 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.2 MB 4.4 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.2 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 4.1 MB/s eta 0:00:00
Downloading camelot_py-2.0.0-py3-none-any.whl (113 kB)
Installing collected packages: playa-pdf, numpy, opencv-python-headless, camelot-py
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Successfully installed camelot-py-2.0.0 numpy-2.4.6 opencv-python-headless-5.0.0.93 playa-pdf-1.1.0

WARNING: camelot-py 2.0.0 does not provide the extra 'cv'
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\sudar\AppData\Local\Programs\Python\Python311\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\sudar\AppData\Local\Programs\Python\Python311\Lib\site-packages\~umpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.6 which is incompatible.
jax 0.4.35 requires ml-dtypes>=0.4.0, but you have ml-dtypes 0.2.0 which is incompatible.
langchain 0.3.13 requires numpy<2,>=1.22.4; python_version < "3.12", but you have numpy 2.4.6 which is incompatible.
langchain-community 0.3.13 requires numpy<2,>=1.22.4; python_version < "3.12", but you have numpy 2.4.6 which is incompatible.
llama-index-llms-gemini 0.4.2 requires pillow<11.0.0,>=10.2.0, but you have pillow 12.3.0 which is incompatible.
matplotlib 3.8.3 requires numpy<2,>=1.21, but you have numpy 2.4.6 which is incompatible.
mediapipe 0.10.7 requires protobuf<4,>=3.11, but you have protobuf 4.25.9 which is incompatible.
pyarrow 15.0.1 requires numpy<2,>=1.16.6, but you have numpy 2.4.6 which is incompatible.
scipy 1.10.1 requires numpy<1.27.0,>=1.19.5, but you have numpy 2.4.6 which is incompatible.
streamlit 1.32.1 requires numpy<2,>=1.19.3, but you have numpy 2.4.6 which is incompatible.
streamlit 1.32.1 requires pandas<3,>=1.3.0, but you have pandas 3.0.5 which is incompatible.
streamlit 1.32.1 requires pillow<11,>=7.1.0, but you have pillow 12.3.0 which is incompatible.
tensorflow-intel 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 2.4.6 which is incompatible.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
!pip install "numpy<2"

Collecting numpy<2
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.6
    Uninstalling numpy-2.4.6:
      Successfully uninstalled numpy-2.4.6
Successfully installed numpy-1.26.4

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\sudar\AppData\Local\Programs\Python\Python311\Lib\site-packages\~-mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\sudar\AppData\Local\Programs\Python\Python311\Lib\site-packages\~-mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.4.35 requires ml-dtypes>=0.4.0, but you have ml-dtypes 0.2.0 which is incompatible.
llama-index-llms-gemini 0.4.2 requires pillow<11.0.0,>=10.2.0, but you have pillow 12.3.0 which is incompatible.
mediapipe 0.10.7 requires protobuf<4,>=3.11, but you have protobuf 4.25.9 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
streamlit 1.32.1 requires pandas<3,>=1.3.0, but you have pandas 3.0.5 which is incompatible.
streamlit 1.32.1 requires pillow<11,>=7.1.0, but you have pillow 12.3.0 which is incompatible.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import camelot

pdf_path = r"data\00007.pdf"

# Extract tables from page 1 using 'lattice' flavor (default)
tables = camelot.read_pdf(pdf_path, pages="1", flavor="lattice")

print(f"Total tables found: {tables.n}")

# Iterate through extracted tables
for i, table in enumerate(tables):
    print(f"\n--- Table {i + 1} ---")
    print(f"Parsing accuracy: {table.parsing_report['accuracy']:.2f}%")
    
    # Convert to a Pandas DataFrame
    df = table.df
    # print(df.head())
    
    # # Export options:
    # # table.to_csv(f"table_{i+1}.csv")
    # # table.to_excel(f"table_{i+1}.xlsx")
    # # table.to_json(f"table_{i+1}.json")

Total tables found: 2

--- Table 1 ---
Parsing accuracy: 97.49%
                      0                   1
0  Account Holders Name   LOAN FINANCE CORP
1           Customer Id           732083910
2           Branch Name  PUNE KOREGAON PARK
3             MICR Code           725126629
4             IFSC Code         VELO0523361

--- Table 2 ---
Parsing accuracy: 99.21%
                      0            1           2  \
0              Txn Date   Value Date  Cheque No.
1  01-01-2024\n11:52:35  01 Jan 2024
2  01-01-2024\n19:21:39  01 Jan 2024
3  02-01-2024\n21:07:21  02 Jan 2024
4  03-01-2024\n10:56:30  03 Jan 2024

                                                   3             4  \
0                                        Description  Branch\nCode
1  RTGS Dr-CNRBR946608852502-HDFC0004171-RAMES\nH...          7892
2                        CASH-BNA-SELF-NISHA JHAVERI          5749
3    IMPS BRN SALARY TRF BY-CONSUMER PRODUCTS\nINDIA          2984
4  RTGS Dr-CNRBR432998576731-HDFC0004171-KETAN\nM...          4156

                5              6               7
0           Debit         Credit         Balance
1   Rs. 41,507.00                 Rs. 143,520.03
2                   Rs. 3,335.80  Rs. 146,855.83
3                  Rs. 18,056.32  Rs. 164,912.15
4  Rs. 127,821.16                  Rs. 37,090.99

In [6]:
df

,0,1,2,3,4,5,6,7
0,Txn Date,Value Date,Cheque No.,Description,Branch\nCode,Debit,Credit,Balance
1,01-01-2024\n11:52:35,01 Jan 2024,,RTGS Dr-CNRBR946608852502-HDFC0004171-RAMES\nH...,7892,"Rs. 41,507.00",,"Rs. 143,520.03"
2,01-01-2024\n19:21:39,01 Jan 2024,,CASH-BNA-SELF-NISHA JHAVERI,5749,,"Rs. 3,335.80","Rs. 146,855.83"
3,02-01-2024\n21:07:21,02 Jan 2024,,IMPS BRN SALARY TRF BY-CONSUMER PRODUCTS\nINDIA,2984,,"Rs. 18,056.32","Rs. 164,912.15"
4,03-01-2024\n10:56:30,03 Jan 2024,,RTGS Dr-CNRBR432998576731-HDFC0004171-KETAN\nM...,4156,"Rs. 127,821.16",,"Rs. 37,090.99"
5,03-01-2024\n16:11:52,03 Jan 2024,,NEFT Dr-714240285711-HDFC0009038-KAVITA AMIN,4156,"Rs. 14,757.45",,"Rs. 22,333.54"
6,05-01-2024\n09:30:00,05 Jan 2024,,NEFT Dr-263381008385-SOFTWARE SUBSCRIPTION,2984,"Rs. 3,078.35",,"Rs. 146,009.66"
7,05-01-2024\n10:00:00,05 Jan 2024,,NEFT Dr-455478138440-RENT PAYMENT-MONTHLY\nRENT,7892,"Rs. 15,795.21",,"Rs. 149,088.01"
8,05-01-2024\n12:17:48,05 Jan 2024,,UPI/CR/414806262214/DHARA\nKOTHARI/SENT-TRANSF...,2984,,Rs. 429.05,"Rs. 22,762.59"
9,05-01-2024\n19:36:43\nSYNTHETIC DATA - MACHINE...,05 Jan 2024,,NEFT Cr-468604178059-ICIC0SF0002-DAILY NEEDS\n...,4156,,"Rs. 7,410.56","Rs. 30,173.15"
10,06-01-2024\n10:39:20,06 Jan 2024,,NEFT Cr-483204537234-ICIC0SF0002-WEBSTREAM\nLI...,7892,,"Rs. 14,236.29","Rs. 44,409.44"
11,06-01-2024\n12:26:03,06 Jan 2024,,ATM WDL-ATM CASH 96012,4156,"Rs. 3,946.72",,"Rs. 40,462.72"
12,06-01-2024\n15:59:22,06 Jan 2024,505605,Chq Paid-MICR Inward Clearing-FORAM JOSHI-HDFC...,4156,"Rs. 15,718.97",,"Rs. 24,743.75"
13,08-01-2024\n11:31:27,08 Jan 2024,,NEFT Cr-159905059627-ICIC0SF0002-RETAIL\nBRAND...,4156,,"Rs. 8,998.31","Rs. 33,742.06"

In [7]:
len(df)

14

In [8]:
import camelot
import pandas as pd

pdf_path = r"data/00007.pdf"

# Extract tables across all pages
tables = camelot.read_pdf(pdf_path, pages="all", flavor="lattice")

print(f"Total tables found across entire PDF: {tables.n}")

# 1. Inspect each extracted table
for i, table in enumerate(tables):
    print(f"\n--- Table {i + 1} (Page {table.page}) ---")
    print(f"Accuracy: {table.parsing_report['accuracy']:.2f}%")
    display(table.df)  # In Jupyter notebook use display(), or print(table.df)

Total tables found across entire PDF: 7

--- Table 1 (Page 1) ---
Accuracy: 97.49%

,0,1
0,Account Holders Name,LOAN FINANCE CORP
1,Customer Id,732083910
2,Branch Name,PUNE KOREGAON PARK
3,MICR Code,725126629
4,IFSC Code,VELO0523361
5,Searched By,From 01 Jan 2024 To 31 Mar 2024
6,Account Number,45868010091
7,Account Currency,INR
8,Product Name\nSYNTHETIC DATA - MACHINE GENERATED,CURRENT ACCOUNT- GENERAL
9,Interest Rate,3.01% p.a.
10,Opening Balance,"Rs. 185,027.03"
11,Closing Balance,"Rs. 105,716.95"

--- Table 2 (Page 1) ---
Accuracy: 99.21%

,0,1,2,3,4,5,6,7
0,Txn Date,Value Date,Cheque No.,Description,Branch\nCode,Debit,Credit,Balance
1,01-01-2024\n11:52:35,01 Jan 2024,,RTGS Dr-CNRBR946608852502-HDFC0004171-RAMES\nH...,7892,"Rs. 41,507.00",,"Rs. 143,520.03"
2,01-01-2024\n19:21:39,01 Jan 2024,,CASH-BNA-SELF-NISHA JHAVERI,5749,,"Rs. 3,335.80","Rs. 146,855.83"
3,02-01-2024\n21:07:21,02 Jan 2024,,IMPS BRN SALARY TRF BY-CONSUMER PRODUCTS\nINDIA,2984,,"Rs. 18,056.32","Rs. 164,912.15"
4,03-01-2024\n10:56:30,03 Jan 2024,,RTGS Dr-CNRBR432998576731-HDFC0004171-KETAN\nM...,4156,"Rs. 127,821.16",,"Rs. 37,090.99"
5,03-01-2024\n16:11:52,03 Jan 2024,,NEFT Dr-714240285711-HDFC0009038-KAVITA AMIN,4156,"Rs. 14,757.45",,"Rs. 22,333.54"
6,05-01-2024\n09:30:00,05 Jan 2024,,NEFT Dr-263381008385-SOFTWARE SUBSCRIPTION,2984,"Rs. 3,078.35",,"Rs. 146,009.66"
7,05-01-2024\n10:00:00,05 Jan 2024,,NEFT Dr-455478138440-RENT PAYMENT-MONTHLY\nRENT,7892,"Rs. 15,795.21",,"Rs. 149,088.01"
8,05-01-2024\n12:17:48,05 Jan 2024,,UPI/CR/414806262214/DHARA\nKOTHARI/SENT-TRANSF...,2984,,Rs. 429.05,"Rs. 22,762.59"
9,05-01-2024\n19:36:43\nSYNTHETIC DATA - MACHINE...,05 Jan 2024,,NEFT Cr-468604178059-ICIC0SF0002-DAILY NEEDS\n...,4156,,"Rs. 7,410.56","Rs. 30,173.15"
10,06-01-2024\n10:39:20,06 Jan 2024,,NEFT Cr-483204537234-ICIC0SF0002-WEBSTREAM\nLI...,7892,,"Rs. 14,236.29","Rs. 44,409.44"
11,06-01-2024\n12:26:03,06 Jan 2024,,ATM WDL-ATM CASH 96012,4156,"Rs. 3,946.72",,"Rs. 40,462.72"
12,06-01-2024\n15:59:22,06 Jan 2024,505605,Chq Paid-MICR Inward Clearing-FORAM JOSHI-HDFC...,4156,"Rs. 15,718.97",,"Rs. 24,743.75"
13,08-01-2024\n11:31:27,08 Jan 2024,,NEFT Cr-159905059627-ICIC0SF0002-RETAIL\nBRAND...,4156,,"Rs. 8,998.31","Rs. 33,742.06"

--- Table 3 (Page 2) ---
Accuracy: 99.02%

,0,1,2,3,4,5,6,7
0,Txn Date,Value Date,Cheque No.,Description,Branch\nCode,Debit,Credit,Balance
1,09-01-2024\n11:35:28,09 Jan 2024,,UPI/CR/979861042993/SEJAL DAVE/SENT-TRANSFER\n...,5749,,Rs. 432.49,"Rs. 34,174.55"
2,09-01-2024\n14:57:13\nSYNTHETIC DATA - MACHINE...,09 Jan 2024,,IMPS Dr-289880163674-NILESH DOSHI,7892,"Rs. 2,474.01",,"Rs. 31,700.54"
3,11-01-2024\n16:41:01,11 Jan 2024,,NEFT Dr-803872716528-HDFC0009038-JAYESH MODI,5749,"Rs. 2,401.52",,"Rs. 29,299.02"
4,13-01-2024\n12:05:38,13 Jan 2024,945613,Chq Paid-MICR Inward Clearing-DHARA\nTHAKKAR-H...,7892,"Rs. 7,750.33",,"Rs. 21,548.69"
5,13-01-2024\n14:36:11,13 Jan 2024,,IMPS Dr-146700252018-NEHA PAREKH,4156,"Rs. 3,102.14",,"Rs. 18,446.55"
6,16-01-2024\n13:16:56,16 Jan 2024,,CASH-BNA-SELF-BHAVESH MODI,2984,,"Rs. 1,076.64","Rs. 19,523.19"
7,16-01-2024\n20:08:55,16 Jan 2024,,RTGS Dr-CNRBR567266128536-HDFC0004171-RITU\nME...,7892,"Rs. 11,918.91",,"Rs. 7,604.28"
8,17-01-2024\n20:22:34,17 Jan 2024,,UPI/CR/775896754688/NILESH\nPARIKH/SENT-TRANSF...,7892,,Rs. 465.03,"Rs. 8,069.31"
9,17-01-2024\n20:44:06,17 Jan 2024,257194,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), COURIER\...",4156,,"Rs. 1,617.78","Rs. 9,687.09"
10,18-01-2024\n14:03:02,18 Jan 2024,,CASH-BNA-SELF-NEHA DESAI,7892,,Rs. 943.94,"Rs. 10,631.03"
11,18-01-2024\n16:26:36,18 Jan 2024,,UPI/CR/151682483772/ASHISH\nDAVE/SENT-TRANSFER...,4156,,Rs. 995.72,"Rs. 11,626.75"
12,18-01-2024\n17:55:31,18 Jan 2024,,IMPS BRN SALARY TRF BY-DAILY NEEDS LIMITED,4156,,"Rs. 2,000.03","Rs. 13,626.78"
13,19-01-2024\n06:37:59,19 Jan 2024,479664,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT),\nCOMMERC...",2984,,"Rs. 2,769.92","Rs. 16,396.70"
14,19-01-2024\n10:44:28,19 Jan 2024,859124,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), CONSUMER...",7892,,Rs. 961.66,"Rs. 17,358.36"
15,19-01-2024\n14:41:20,19 Jan 2024,,CASH-BNA-SELF-BHAVESH TRIVEDI,4156,,"Rs. 1,166.40","Rs. 18,524.76"
16,22-01-2024\n12:08:35\nSYNTHETIC DATA - MACHINE...,22 Jan 2024,,Cash Withdrawal-RIDDHI MEHTA,4156,Rs. 183.38,,"Rs. 18,341.38"
17,22-01-2024\n12:14:02,22 Jan 2024,518820,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), PROPERTY...",2984,,"Rs. 3,634.60","Rs. 21,975.98"
18,23-01-2024\n21:44:04,23 Jan 2024,,Cash Withdrawal-SEJAL GANDHI,5749,"Rs. 1,082.46",,"Rs. 20,893.52"
19,24-01-2024\n07:22:49,24 Jan 2024,714996,Chq Paid-MICR Inward Clearing-RIDDHI BHATT-HDF...,4156,"Rs. 5,744.09",,"Rs. 15,149.43"
20,24-01-2024\n12:37:31,24 Jan 2024,,CASH-BNA-SELF-ANJALI SHUKLA,2984,,Rs. 201.57,"Rs. 15,351.00"
21,24-01-2024\n14:42:01,24 Jan 2024,,NEFT Cr-827158472265-ICIC0SF0002-FINANCIAL\nPR...,5749,,"Rs. 2,749.34","Rs. 18,100.34"
22,24-01-2024\n16:40:20,24 Jan 2024,,NEFT Cr-459863740335-ICIC0SF0002-MEDICAL\nSOLU...,5749,,"Rs. 3,691.37","Rs. 21,791.71"
23,24-01-2024\n17:08:31,24 Jan 2024,,NEFT Cr-503069610507-ICIC0SF0002-TRADING\nHOUS...,2984,,"Rs. 3,070.80","Rs. 24,862.51"
24,25-01-2024\n12:55:53,25 Jan 2024,,CASH-BNA-SELF-POOJA BHATT,7892,,"Rs. 2,028.27","Rs. 26,890.78"
25,25-01-2024\n15:47:33,25 Jan 2024,856298,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), FINANCIA...",2984,,"Rs. 7,397.40","Rs. 34,288.18"
26,25-01-2024\n15:56:59,25 Jan 2024,,UPI/CR/719903389674/RAKESH\nVORA/SENT-TRANSFER...,4156,,Rs. 729.77,"Rs. 35,017.95"
27,27-01-2024\n07:44:11,27 Jan 2024,,NEFT Cr-850754548557-ICIC0SF0002-URBAN\nCONSTR...,4156,,"Rs. 15,536.05","Rs. 50,554.00"
28,27-01-2024\n10:50:36,27 Jan 2024,,IMPS Dr-772299691570-PRIYA VORA,2984,"Rs. 6,305.98",,"Rs. 44,248.02"
29,29-01-2024\n10:38:04\nSYNTHETIC DATA - MACHINE...,29 Jan 2024,,IMPS BRN SALARY TRF BY-NETFORGE\nTECHNOLOGIES,7892,,"Rs. 3,121.14","Rs. 47,369.16"
30,29-01-2024\n13:21:42,29 Jan 2024,,NEFT Cr-183753116180-ICIC0SF0002-PREMIUM\nPROP...,4156,,"Rs. 10,043.04","Rs. 57,412.20"
31,29-01-2024\n13:32:21,29 Jan 2024,,NEFT Dr-458456967032-HDFC0009038-NEHA PAREKH,2984,"Rs. 18,646.88",,"Rs. 38,765.32"
32,29-01-2024\n14:39:46,29 Jan 2024,,IMPS BRN SALARY TRF BY-FOUNDATION\nPROJECTS LTD,4156,,"Rs. 4,460.99","Rs. 43,226.31"
33,29-01-2024\n15:41:02,29 Jan 2024,,IMPS BRN SALARY TRF BY-DATABRIDGE INFOTECH,5749,,"Rs. 8,132.86","Rs. 51,359.17"

--- Table 4 (Page 3) ---
Accuracy: 99.04%

,0,1,2,3,4,5,6,7
0,Txn Date,Value Date,Cheque No.,Description,Branch\nCode,Debit,Credit,Balance
1,29-01-2024\n16:48:01,29 Jan 2024,,IMPS BRN SALARY TRF BY-FASHION TEXTILES LTD,4156,,"Rs. 3,585.98","Rs. 54,945.15"
2,29-01-2024\n21:10:32\nSYNTHETIC DATA - MACHINE...,29 Jan 2024,,IMPS BRN SALARY TRF BY-PREMIUM PROPERTIES\nLTD,7892,,Rs. 787.18,"Rs. 55,732.33"
3,30-01-2024\n10:09:59,30 Jan 2024,307903,Chq Paid-MICR Inward Clearing-KAVITA VORA-HDFC...,5749,"Rs. 9,158.83",,"Rs. 46,573.50"
4,30-01-2024\n11:27:51,30 Jan 2024,,NEFT Cr-463990380908-ICIC0SF0002-REMEDIES\nHEA...,2984,,"Rs. 11,607.69","Rs. 58,181.19"
5,30-01-2024\n12:47:29,30 Jan 2024,,IMPS BRN SALARY TRF BY-WELLNESS BRANDS\nINDIA,4156,,"Rs. 6,687.23","Rs. 64,868.42"
6,30-01-2024\n14:36:58,30 Jan 2024,918427,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT),\nHEALTHC...",4156,,"Rs. 5,298.11","Rs. 70,166.53"
7,31-01-2024\n11:43:17,31 Jan 2024,,IMPS BRN SALARY TRF BY-CYBERCRAFT SYSTEMS,4156,,"Rs. 8,735.32","Rs. 78,901.85"
8,31-01-2024\n14:03:35,31 Jan 2024,,RTGS Cr-ICICR542957782860-ICIC0000011-ESTATE\n...,2984,,"Rs. 101,116.73","Rs. 180,018.58"
9,01-02-2024\n09:37:14,01 Feb 2024,604799,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), TRADING\...",4156,,"Rs. 28,156.85","Rs. 208,175.43"
10,01-02-2024\n14:03:30,01 Feb 2024,,IMPS Dr-274012913196-NEHA DOSHI,4156,"Rs. 2,284.65",,"Rs. 205,890.78"
11,03-02-2024\n06:17:56,03 Feb 2024,290969,Chq Paid-MICR Inward Clearing-DINESH\nPAREKH-H...,5749,"Rs. 86,641.94",,"Rs. 119,248.84"
12,03-02-2024\n19:32:49,03 Feb 2024,,FAILED-INSUFFICIENT FUNDS-RTGS\nDr-CNRBR894402...,2984,,,"Rs. 119,248.84"
13,05-02-2024\n09:30:00,05 Feb 2024,,NEFT Dr-183051936764-SOFTWARE SUBSCRIPTION,2984,"Rs. 4,884.27",,"Rs. 125,330.18"
14,05-02-2024\n10:00:00,05 Feb 2024,,NEFT Dr-375824877917-RENT PAYMENT-MONTHLY\nRENT,2984,"Rs. 15,795.21",,"Rs. 130,214.45"
15,05-02-2024\n16:32:26\nSYNTHETIC DATA - MACHINE...,05 Feb 2024,,IMPS Dr-373928384628-FORAM VYAS,7892,"Rs. 12,398.92",,"Rs. 106,849.92"
16,06-02-2024\n11:05:24,06 Feb 2024,,IMPS Dr-511590108367-MANISH VYAS,2984,"Rs. 5,130.01",,"Rs. 101,719.91"
17,06-02-2024\n11:08:34,06 Feb 2024,,NEFT Cr-888541071823-ICIC0SF0002-DAIRY\nPRODUC...,7892,,"Rs. 40,389.77","Rs. 142,109.68"
18,07-02-2024\n11:31:02,07 Feb 2024,,IMPS Dr-296242301983-HIRAL PAREKH,7892,"Rs. 16,999.00",,"Rs. 125,110.68"
19,07-02-2024\n11:48:40,07 Feb 2024,,RTGS Dr-CNRBR524442597943-HDFC0004171-MANIS\nH...,7892,"Rs. 25,567.77",,"Rs. 99,542.91"
20,07-02-2024\n11:57:27,07 Feb 2024,,IMPS BRN SALARY TRF BY-PREMIUM\nINFRASTRUCTURE,4156,,"Rs. 4,250.80","Rs. 103,793.71"
21,10-02-2024\n14:33:57,10 Feb 2024,851466,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), ROADWAY\...",7892,,"Rs. 29,882.04","Rs. 133,675.75"
22,10-02-2024\n17:31:57,10 Feb 2024,,UPI/CR/183335850344/SHRUTI\nMODI/SENT-TRANSFER...,5749,,"Rs. 1,903.33","Rs. 135,579.08"
23,10-02-2024\n17:52:19,10 Feb 2024,,NEFT Dr-141816810875-HDFC0009038-RIDDHI\nKOTHARI,4156,"Rs. 54,014.00",,"Rs. 81,565.08"
24,12-02-2024\n09:04:17,12 Feb 2024,,UPI/CR/946682810709/DHARA\nPATEL/SENT-TRANSFER...,7892,,"Rs. 3,656.48","Rs. 85,221.56"
25,12-02-2024\n11:43:37,12 Feb 2024,,NEFT Dr-314059496623-HDFC0009038-ASHISH\nTHAKKAR,7892,"Rs. 17,975.56",,"Rs. 67,246.00"
26,12-02-2024\n20:37:37,12 Feb 2024,390602,Chq Paid-MICR Inward Clearing-HIRAL RAVAL-HDFC...,4156,"Rs. 6,102.89",,"Rs. 61,143.11"
27,13-02-2024\n08:32:58,13 Feb 2024,,UPI/CR/728484373466/RITU DAVE/SENT-TRANSFER\nF...,2984,,"Rs. 2,781.43","Rs. 63,924.54"
28,13-02-2024\n11:41:01,13 Feb 2024,,NEFT Cr-476092739012-ICIC0SF0002-HEALTHPLUS\nP...,4156,,"Rs. 11,416.91","Rs. 75,341.45"
29,14-02-2024\n12:01:43\nSYNTHETIC DATA - MACHINE...,14 Feb 2024,117253,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), GATEWAY\...",5749,,"Rs. 7,434.80","Rs. 82,776.25"
30,14-02-2024\n13:12:28,14 Feb 2024,,RTGS Cr-ICICR693724741445-ICIC0000011-URBAN\nE...,2984,,"Rs. 90,872.90","Rs. 173,649.15"
31,14-02-2024\n15:28:34,14 Feb 2024,692136,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), MOTOR\nI...",2984,,"Rs. 19,881.12","Rs. 193,530.27"
32,15-02-2024\n10:17:04,15 Feb 2024,,Cash Withdrawal-RAJESH JOSHI,5749,"Rs. 2,954.49",,"Rs. 190,575.78"
33,15-02-2024\n11:47:14,15 Feb 2024,,IMPS Dr-686278434411-NILESH KOTHARI,2984,"Rs. 2,522.96",,"Rs. 188,052.82"

--- Table 5 (Page 4) ---
Accuracy: 99.03%

,0,1,2,3,4,5,6,7
0,Txn Date,Value Date,Cheque No.,Description,Branch\nCode,Debit,Credit,Balance
1,15-02-2024\n12:46:18,15 Feb 2024,,UPI/DR/828278755083/RAMESH\nTHAKKAR/UPI-TRANSF...,5749,"Rs. 1,283.54",,"Rs. 186,769.28"
2,15-02-2024\n13:26:49\nSYNTHETIC DATA - MACHINE...,15 Feb 2024,186213,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), SKYLINE\...",7892,,"Rs. 19,857.99","Rs. 206,627.27"
3,15-02-2024\n20:04:32,15 Feb 2024,,IMPS BRN SALARY TRF BY-MINDWAVE CONSULTING,2984,,"Rs. 7,509.60","Rs. 214,136.87"
4,17-02-2024\n13:05:13,17 Feb 2024,,IMPS Dr-121135076031-DHARA JOSHI,4156,"Rs. 24,691.31",,"Rs. 189,445.56"
5,19-02-2024\n13:45:09,19 Feb 2024,342326,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), THERMAL\...",7892,,"Rs. 31,971.09","Rs. 221,416.65"
6,20-02-2024\n10:20:51,20 Feb 2024,,Cash Withdrawal-NISHA DESAI,5749,"Rs. 7,654.24",,"Rs. 213,762.41"
7,20-02-2024\n12:14:55,20 Feb 2024,,RTGS Cr-ICICR366090552313-ICIC0000011-PREMIUM\...,5749,,"Rs. 166,506.25","Rs. 380,268.66"
8,20-02-2024\n13:45:09,20 Feb 2024,342326,"REVERSAL-By Clg:DEL ACCTS-CITI BANK N.A.(CIT),...",7892,"Rs. 31,971.09",,"Rs. 164,883.22"
9,21-02-2024\n15:09:36,21 Feb 2024,161643,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), FINANCIA...",7892,,"Rs. 27,629.26","Rs. 407,897.92"
10,21-02-2024\n16:13:15,21 Feb 2024,606129,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), MEDCARE\...",2984,,"Rs. 106,049.75","Rs. 513,947.67"
11,22-02-2024\n13:22:49,22 Feb 2024,,IMPS BRN SALARY TRF BY-CLOUDTECH SERVICES,4156,,"Rs. 39,723.91","Rs. 553,671.58"
12,22-02-2024\n15:31:48,22 Feb 2024,,CASH-BNA-SELF-KAVITA SHAH,5749,,"Rs. 10,528.53","Rs. 564,200.11"
13,22-02-2024\n15:32:29,22 Feb 2024,,NEFT Dr-404016394949-HDFC0009038-FORAM\nKOTHARI,2984,"Rs. 63,242.90",,"Rs. 500,957.21"
14,22-02-2024\n16:21:18,22 Feb 2024,339274,Chq Paid-MICR Inward Clearing-MEHUL DAVE-HDFC\...,2984,"Rs. 188,256.27",,"Rs. 312,700.94"
15,22-02-2024\n19:18:22,22 Feb 2024,,RTGS Dr-CNRBR320016707853-HDFC0004171-RIDDHI\n...,4156,"Rs. 134,563.00",,"Rs. 178,137.94"
16,23-02-2024\n20:11:52\nSYNTHETIC DATA - MACHINE...,23 Feb 2024,,UPI/CR/201288050245/KETAN\nPAREKH/SENT-TRANSFE...,4156,,"Rs. 3,115.00","Rs. 181,252.94"
17,24-02-2024\n07:49:25,24 Feb 2024,,IMPS BRN SALARY TRF BY-VITALITY MEDICINES LTD,4156,,"Rs. 14,404.36","Rs. 195,657.30"
18,24-02-2024\n12:17:50,24 Feb 2024,,RTGS Cr-ICICR481689445330-ICIC0000011-CARGO\nS...,7892,,"Rs. 256,398.13","Rs. 452,055.43"
19,24-02-2024\n15:47:01,24 Feb 2024,311676,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), CLOTHING...",4156,,"Rs. 91,053.91","Rs. 543,109.34"
20,26-02-2024\n07:28:18,26 Feb 2024,,NEFT Dr-436939128771-HDFC0009038-NEHA JHAVERI,4156,"Rs. 172,173.32",,"Rs. 370,936.02"
21,26-02-2024\n10:11:55,26 Feb 2024,143535,Chq Paid-MICR Inward Clearing-RAKESH PATEL-HDF...,2984,"Rs. 120,961.91",,"Rs. 249,974.11"
22,26-02-2024\n13:46:14,26 Feb 2024,,NEFT Dr-653637243614-HDFC0009038-SURESH\nPAREKH,4156,"Rs. 27,677.13",,"Rs. 222,296.98"
23,26-02-2024\n14:46:33,26 Feb 2024,,IMPS BRN SALARY TRF BY-DAIRY PRODUCTS INDIA,5749,,"Rs. 18,849.99","Rs. 241,146.97"
24,27-02-2024\n19:57:08,27 Feb 2024,,UPI/DR/721407675120/SURESH\nDESAI/UPI-TRANSFER...,7892,"Rs. 5,573.01",,"Rs. 235,573.96"
25,28-02-2024\n11:54:28,28 Feb 2024,840705,Chq Paid-MICR Inward Clearing-MEHUL PATEL-HDFC...,4156,"Rs. 84,795.31",,"Rs. 150,778.65"
26,28-02-2024\n13:19:58,28 Feb 2024,,IMPS BRN SALARY TRF BY-FASHION TEXTILES LTD,7892,,"Rs. 2,214.33","Rs. 152,992.98"
27,28-02-2024\n23:59:00,28 Feb 2024,,Service Charges-Online Banking Charges,4156,Rs. 122.24,,"Rs. 106,554.31"
28,28-02-2024\n23:59:00,28 Feb 2024,,Service Charges-Cheque Book Charges,4156,Rs. 197.12,,"Rs. 106,357.19"
29,29-02-2024\n11:41:43\nSYNTHETIC DATA - MACHINE...,29 Feb 2024,,CASH-BNA-SELF-HIRAL SHAH,7892,,"Rs. 2,670.26","Rs. 155,663.24"
30,01-03-2024\n12:18:33,01 Mar 2024,,RTGS Cr-ICICR622876014764-ICIC0000011-HEALTHC\...,4156,,"Rs. 72,043.60","Rs. 227,706.84"
31,01-03-2024\n12:22:02,01 Mar 2024,,NEFT Cr-255905911666-ICIC0SF0002-CITYSCAPE\nDE...,2984,,"Rs. 16,654.77","Rs. 244,361.61"
32,01-03-2024\n14:37:17,01 Mar 2024,,NEFT Dr-787471598207-HDFC0009038-FORAM AMIN,5749,"Rs. 78,972.59",,"Rs. 165,389.02"
33,01-03-2024\n21:39:15,01 Mar 2024,,UPI/DR/249685449606/ANJALI DAVE/UPI-TRANSFER\n...,4156,"Rs. 3,073.16",,"Rs. 162,315.86"

--- Table 6 (Page 5) ---
Accuracy: 99.04%

,0,1,2,3,4,5,6,7
0,Txn Date,Value Date,Cheque No.,Description,Branch\nCode,Debit,Credit,Balance
1,04-03-2024\n16:48:42,04 Mar 2024,,IMPS BRN SALARY TRF BY-MECHANICAL\nSOLUTIONS LTD,2984,,"Rs. 7,737.67","Rs. 170,053.53"
2,05-03-2024\n09:30:00\nSYNTHETIC DATA - MACHINE...,05 Mar 2024,,NEFT Dr-968097893929-UTILITY PAYMENT,4156,"Rs. 2,858.42",,"Rs. 106,676.55"
3,05-03-2024\n10:00:00,05 Mar 2024,,NEFT Dr-439315451508-RENT PAYMENT-MONTHLY\nRENT,5749,"Rs. 15,795.21",,"Rs. 109,534.97"
4,05-03-2024\n11:08:48,05 Mar 2024,364501,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), MARKET\n...",2984,,"Rs. 36,156.06","Rs. 206,209.59"
5,06-03-2024\n14:00:14,06 Mar 2024,,NEFT Cr-216958671661-ICIC0SF0002-CONSUMER\nESS...,4156,,"Rs. 44,169.43","Rs. 250,379.02"
6,07-03-2024\n19:33:11,07 Mar 2024,514189,Chq Paid-MICR Inward Clearing-FORAM BHATT-HDFC...,2984,"Rs. 100,071.17",,"Rs. 150,307.85"
7,09-03-2024\n12:28:29,09 Mar 2024,,CASH-BNA-SELF-DINESH MODI,7892,,"Rs. 5,105.90","Rs. 155,413.75"
8,12-03-2024\n06:40:39,12 Mar 2024,,NEFT Cr-621652011249-ICIC0SF0002-FASHION\nTEXT...,5749,,"Rs. 68,498.72","Rs. 223,912.47"
9,12-03-2024\n16:01:45,12 Mar 2024,,NEFT Dr-585581881100-HDFC0009038-RITU PATEL,4156,"Rs. 37,748.91",,"Rs. 186,163.56"
10,13-03-2024\n06:14:16,13 Mar 2024,,UPI/CR/337638713566/HITESH\nKOTHARI/SENT-TRANS...,4156,,"Rs. 1,597.73","Rs. 187,761.29"
11,13-03-2024\n10:31:05,13 Mar 2024,874625,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT),\nRESIDEN...",7892,,"Rs. 21,790.43","Rs. 209,551.72"
12,14-03-2024\n07:36:37,14 Mar 2024,,RTGS Dr-CNRBR618421233526-HDFC0004171-RAJES\nH...,5749,"Rs. 42,634.32",,"Rs. 166,917.40"
13,14-03-2024\n11:23:43,14 Mar 2024,,UPI/DR/609360049714/KAVITA\nGANDHI/UPI-TRANSFE...,2984,Rs. 835.60,,"Rs. 166,081.80"
14,14-03-2024\n11:29:58,14 Mar 2024,,RTGS Dr-CNRBR860960705062-HDFC0004171-PRIYA\nM...,2984,"Rs. 95,771.32",,"Rs. 70,310.48"
15,14-03-2024\n12:45:18,14 Mar 2024,,RTGS Cr-ICICR943375445599-ICIC0000011-INVESTME...,5749,,"Rs. 46,472.20","Rs. 116,782.68"
16,15-03-2024\n08:16:24\nSYNTHETIC DATA - MACHINE...,15 Mar 2024,,ATM WDL-ATM CASH 10945,2984,"Rs. 6,342.05",,"Rs. 110,440.63"
17,15-03-2024\n12:30:34,15 Mar 2024,,ATM WDL-ATM CASH 41736,5749,"Rs. 18,660.29",,"Rs. 91,780.34"
18,15-03-2024\n15:32:00,15 Mar 2024,968871,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT),\nFOUNDAT...",4156,,"Rs. 10,762.75","Rs. 102,543.09"
19,15-03-2024\n16:57:45,15 Mar 2024,,RTGS Dr-CNRBR771361910670-HDFC0004171-KAVITA\n...,7892,"Rs. 35,634.34",,"Rs. 66,908.75"
20,16-03-2024\n10:02:51,16 Mar 2024,,CASH-BNA-SELF-ASHISH KOTHARI,2984,,"Rs. 2,607.43","Rs. 69,516.18"
21,16-03-2024\n13:28:04,16 Mar 2024,,UPI/CR/131562115579/PRIYA\nMEHTA/SENT-TRANSFER...,5749,,Rs. 604.90,"Rs. 70,121.08"
22,16-03-2024\n15:31:06,16 Mar 2024,664158,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), MOTOR\nI...",4156,,"Rs. 11,771.92","Rs. 81,893.00"
23,16-03-2024\n16:15:54,16 Mar 2024,,IMPS BRN SALARY TRF BY-POWER SYSTEMS CORP,4156,,"Rs. 7,898.54","Rs. 89,791.54"
24,16-03-2024\n17:01:17,16 Mar 2024,840317,Chq Paid-MICR Inward Clearing-HIRAL JOSHI-HDFC...,5749,"Rs. 43,840.58",,"Rs. 45,950.96"
25,16-03-2024\n17:36:21,16 Mar 2024,,NEFT Cr-195884765738-ICIC0SF0002-WELLNESS\nBRA...,5749,,"Rs. 13,123.05","Rs. 59,074.01"
26,18-03-2024\n11:41:37,18 Mar 2024,,NEFT Cr-803443967715-ICIC0SF0002-GATEWAY\nPROJ...,5749,,"Rs. 6,406.30","Rs. 65,480.31"
27,19-03-2024\n13:46:34,19 Mar 2024,,CASH-BNA-SELF-MEHUL PANDYA,2984,,"Rs. 6,039.73","Rs. 71,520.04"
28,19-03-2024\n18:27:44,19 Mar 2024,359009,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), LOAN\nFI...",2984,,"Rs. 13,315.02","Rs. 84,835.06"
29,20-03-2024\n07:52:00\nSYNTHETIC DATA - MACHINE...,20 Mar 2024,,RTGS Cr-ICICR474872037360-ICIC0000011-INVESTME...,2984,,"Rs. 119,484.88","Rs. 204,319.94"
30,20-03-2024\n09:14:21,20 Mar 2024,,IMPS BRN SALARY TRF BY-TRADING HOUSE LTD,4156,,"Rs. 25,402.66","Rs. 229,722.60"
31,20-03-2024\n11:53:37,20 Mar 2024,515582,Chq Paid-MICR Inward Clearing-JAYESH VORA-HDFC...,2984,"Rs. 45,085.81",,"Rs. 184,636.79"
32,20-03-2024\n14:01:24,20 Mar 2024,382525,Chq Paid-MICR Inward Clearing-BHAVESH\nTHAKKAR...,2984,"Rs. 86,106.32",,"Rs. 98,530.47"
33,20-03-2024\n15:28:13,20 Mar 2024,,NEFT Dr-765859533572-HDFC0009038-SEJAL PATEL,5749,"Rs. 20,556.51",,"Rs. 77,973.96"

--- Table 7 (Page 6) ---
Accuracy: 98.80%

,0,1,2,3,4,5,6,7
0,Txn Date,Value Date,Cheque No.,Description,Branch\nCode,Debit,Credit,Balance
1,20-03-2024\n19:47:26,20 Mar 2024,699171,Chq Paid-MICR Inward Clearing-KAVITA\nKOTHARI-...,4156,"Rs. 27,644.79",,"Rs. 50,329.17"
2,21-03-2024\n14:20:43\nSYNTHETIC DATA - MACHINE...,21 Mar 2024,,NEFT Dr-531372603092-HDFC0009038-SHRUTI\nMEHTA,2984,"Rs. 13,902.50",,"Rs. 36,426.67"
3,22-03-2024\n10:04:08,22 Mar 2024,,ATM WDL-ATM CASH 63232,7892,"Rs. 6,317.97",,"Rs. 30,108.70"
4,22-03-2024\n14:01:25,22 Mar 2024,,RTGS Cr-ICICR521678794498-ICIC0000011-WELLNES\...,5749,,"Rs. 39,422.74","Rs. 69,531.44"
5,23-03-2024\n12:09:39,23 Mar 2024,,UPI/CR/754928451139/ASHISH\nAMIN/SENT-TRANSFER...,7892,,"Rs. 2,798.36","Rs. 72,329.80"
6,26-03-2024\n10:25:10,26 Mar 2024,640414,"By Clg:DEL ACCTS-CITI BANK N.A.(CIT), LOAN\nFI...",4156,,"Rs. 21,248.69","Rs. 93,578.49"
7,26-03-2024\n13:00:39,26 Mar 2024,,IMPS BRN SALARY TRF BY-COMMERCE SOLUTIONS\nLTD,7892,,"Rs. 6,498.74","Rs. 100,077.23"
8,26-03-2024\n13:32:02,26 Mar 2024,,RTGS Cr-ICICR288651860328-ICIC0000011-THERMAL\...,7892,,"Rs. 93,325.86","Rs. 193,403.09"
9,26-03-2024\n20:56:03,26 Mar 2024,,RTGS Cr-ICICR551466677126-ICIC0000011-HEALTHC\...,5749,,"Rs. 180,100.36","Rs. 373,503.45"
10,27-03-2024\n11:44:40,27 Mar 2024,329718,Chq Paid-MICR Inward Clearing-NISHA MEHTA-HDFC...,2984,"Rs. 183,274.74",,"Rs. 190,228.71"
11,28-03-2024\n06:50:53,28 Mar 2024,400069,Chq Paid-MICR Inward Clearing-PARESH\nPARIKH-H...,7892,"Rs. 19,851.49",,"Rs. 170,377.22"
12,28-03-2024\n09:20:05,28 Mar 2024,,IMPS BRN SALARY TRF BY-BUILDING SOLUTIONS\nLTD,4156,,"Rs. 6,279.45","Rs. 176,656.67"
13,28-03-2024\n11:45:35,28 Mar 2024,,NEFT Cr-956271217485-ICIC0SF0002-PREMIUM\nINFR...,2984,,"Rs. 16,512.67","Rs. 193,169.34"
14,28-03-2024\n11:58:22,28 Mar 2024,,UPI/CR/686927672848/ANJALI\nPATEL/SENT-TRANSFE...,4156,,"Rs. 3,684.97","Rs. 196,854.31"
15,28-03-2024\n23:59:00,28 Mar 2024,,Service Charges-Foreign Currency Markup,7892,Rs. 300.00,,"Rs. 106,057.19"
16,28-03-2024\n23:59:00\nSYNTHETIC DATA - MACHINE...,28 Mar 2024,,Service Charges-Statement Charges,2984,Rs. 149.98,,"Rs. 105,907.21"
17,28-03-2024\n23:59:00,28 Mar 2024,,Service Charges-Online Banking Charges,5749,Rs. 190.26,,"Rs. 105,716.95"

In [9]:
# Combine all extracted tables
all_dfs = [table.df for table in tables]
combined_df = pd.concat(all_dfs, ignore_index=True)

# Save to Excel
combined_df.to_excel("extracted_full.xlsx", index=False)